// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func WireApp() *App {
	config := NewConfig()
	mysqlClient := NewMysqlClient(config)
	redisClient := NewRedisClient(config)
	app := NewApp(mysqlClient, redisClient)
	return app
}
