// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: article/v1/article.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Like          int64                  `protobuf:"varint,4,opt,name=like,proto3" json:"like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_article_v1_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetLike() int64 {
	if x != nil {
		return x.Like
	}
	return 0
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_article_v1_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateArticleReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=Article,proto3" json:"Article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleReplay) Reset() {
	*x = CreateArticleReplay{}
	mi := &file_article_v1_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReplay) ProtoMessage() {}

func (x *CreateArticleReplay) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReplay.ProtoReflect.Descriptor instead.
func (*CreateArticleReplay) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleReplay) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_article_v1_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateArticleReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=Article,proto3" json:"Article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleReplay) Reset() {
	*x = UpdateArticleReplay{}
	mi := &file_article_v1_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReplay) ProtoMessage() {}

func (x *UpdateArticleReplay) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReplay.ProtoReflect.Descriptor instead.
func (*UpdateArticleReplay) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateArticleReplay) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_article_v1_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteArticleReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleReplay) Reset() {
	*x = DeleteArticleReplay{}
	mi := &file_article_v1_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleReplay) ProtoMessage() {}

func (x *DeleteArticleReplay) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleReplay.ProtoReflect.Descriptor instead.
func (*DeleteArticleReplay) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{6}
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_article_v1_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=Article,proto3" json:"Article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReplay) Reset() {
	*x = GetArticleReplay{}
	mi := &file_article_v1_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReplay) ProtoMessage() {}

func (x *GetArticleReplay) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReplay.ProtoReflect.Descriptor instead.
func (*GetArticleReplay) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{8}
}

func (x *GetArticleReplay) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ListArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleRequest) Reset() {
	*x = ListArticleRequest{}
	mi := &file_article_v1_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleRequest) ProtoMessage() {}

func (x *ListArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleRequest.ProtoReflect.Descriptor instead.
func (*ListArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{9}
}

type ListArticleReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListArticle   []*Article             `protobuf:"bytes,1,rep,name=listArticle,proto3" json:"listArticle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleReplay) Reset() {
	*x = ListArticleReplay{}
	mi := &file_article_v1_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleReplay) ProtoMessage() {}

func (x *ListArticleReplay) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleReplay.ProtoReflect.Descriptor instead.
func (*ListArticleReplay) Descriptor() ([]byte, []int) {
	return file_article_v1_article_proto_rawDescGZIP(), []int{10}
}

func (x *ListArticleReplay) GetListArticle() []*Article {
	if x != nil {
		return x.ListArticle
	}
	return nil
}

var File_article_v1_article_proto protoreflect.FileDescriptor

const file_article_v1_article_proto_rawDesc = "" +
	"\n" +
	"\x18article/v1/article.proto\x12\n" +
	"article.v1\x1a\x1cgoogle/api/annotations.proto\"]\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04like\x18\x04 \x01(\x03R\x04like\"F\n" +
	"\x14CreateArticleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"D\n" +
	"\x13CreateArticleReplay\x12-\n" +
	"\aArticle\x18\x01 \x01(\v2\x13.article.v1.ArticleR\aArticle\"V\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"D\n" +
	"\x13UpdateArticleReplay\x12-\n" +
	"\aArticle\x18\x01 \x01(\v2\x13.article.v1.ArticleR\aArticle\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13DeleteArticleReplay\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x10GetArticleReplay\x12-\n" +
	"\aArticle\x18\x01 \x01(\v2\x13.article.v1.ArticleR\aArticle\"\x14\n" +
	"\x12ListArticleRequest\"J\n" +
	"\x11ListArticleReplay\x125\n" +
	"\vlistArticle\x18\x01 \x03(\v2\x13.article.v1.ArticleR\vlistArticle2\xa2\x04\n" +
	"\x0eArticleService\x12j\n" +
	"\rCreateArticle\x12 .article.v1.CreateArticleRequest\x1a\x1f.article.v1.CreateArticleReplay\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/article\x12n\n" +
	"\rUpdateArticle\x12 .article.v1.UpdateArticleRequest\x1a\x1f.article.v1.UpdateArticleReplay\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/v1/article{id}\x12l\n" +
	"\rDeleteArticle\x12 .article.v1.DeleteArticleRequest\x1a\x1f.article.v1.DeleteArticleReplay\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/article/{id}\x12c\n" +
	"\n" +
	"GetArticle\x12\x1d.article.v1.GetArticleRequest\x1a\x1c.article.v1.GetArticleReplay\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/article/{id}\x12a\n" +
	"\vListArticle\x12\x1e.article.v1.ListArticleRequest\x1a\x1d.article.v1.ListArticleReplay\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/articleB&Z$moody-blog-article/api/article/v1;v1b\x06proto3"

var (
	file_article_v1_article_proto_rawDescOnce sync.Once
	file_article_v1_article_proto_rawDescData []byte
)

func file_article_v1_article_proto_rawDescGZIP() []byte {
	file_article_v1_article_proto_rawDescOnce.Do(func() {
		file_article_v1_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_v1_article_proto_rawDesc), len(file_article_v1_article_proto_rawDesc)))
	})
	return file_article_v1_article_proto_rawDescData
}

var file_article_v1_article_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_article_v1_article_proto_goTypes = []any{
	(*Article)(nil),              // 0: article.v1.Article
	(*CreateArticleRequest)(nil), // 1: article.v1.CreateArticleRequest
	(*CreateArticleReplay)(nil),  // 2: article.v1.CreateArticleReplay
	(*UpdateArticleRequest)(nil), // 3: article.v1.UpdateArticleRequest
	(*UpdateArticleReplay)(nil),  // 4: article.v1.UpdateArticleReplay
	(*DeleteArticleRequest)(nil), // 5: article.v1.DeleteArticleRequest
	(*DeleteArticleReplay)(nil),  // 6: article.v1.DeleteArticleReplay
	(*GetArticleRequest)(nil),    // 7: article.v1.GetArticleRequest
	(*GetArticleReplay)(nil),     // 8: article.v1.GetArticleReplay
	(*ListArticleRequest)(nil),   // 9: article.v1.ListArticleRequest
	(*ListArticleReplay)(nil),    // 10: article.v1.ListArticleReplay
}
var file_article_v1_article_proto_depIdxs = []int32{
	0,  // 0: article.v1.CreateArticleReplay.Article:type_name -> article.v1.Article
	0,  // 1: article.v1.UpdateArticleReplay.Article:type_name -> article.v1.Article
	0,  // 2: article.v1.GetArticleReplay.Article:type_name -> article.v1.Article
	0,  // 3: article.v1.ListArticleReplay.listArticle:type_name -> article.v1.Article
	1,  // 4: article.v1.ArticleService.CreateArticle:input_type -> article.v1.CreateArticleRequest
	3,  // 5: article.v1.ArticleService.UpdateArticle:input_type -> article.v1.UpdateArticleRequest
	5,  // 6: article.v1.ArticleService.DeleteArticle:input_type -> article.v1.DeleteArticleRequest
	7,  // 7: article.v1.ArticleService.GetArticle:input_type -> article.v1.GetArticleRequest
	9,  // 8: article.v1.ArticleService.ListArticle:input_type -> article.v1.ListArticleRequest
	2,  // 9: article.v1.ArticleService.CreateArticle:output_type -> article.v1.CreateArticleReplay
	4,  // 10: article.v1.ArticleService.UpdateArticle:output_type -> article.v1.UpdateArticleReplay
	6,  // 11: article.v1.ArticleService.DeleteArticle:output_type -> article.v1.DeleteArticleReplay
	8,  // 12: article.v1.ArticleService.GetArticle:output_type -> article.v1.GetArticleReplay
	10, // 13: article.v1.ArticleService.ListArticle:output_type -> article.v1.ListArticleReplay
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_article_v1_article_proto_init() }
func file_article_v1_article_proto_init() {
	if File_article_v1_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_v1_article_proto_rawDesc), len(file_article_v1_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_v1_article_proto_goTypes,
		DependencyIndexes: file_article_v1_article_proto_depIdxs,
		MessageInfos:      file_article_v1_article_proto_msgTypes,
	}.Build()
	File_article_v1_article_proto = out.File
	file_article_v1_article_proto_goTypes = nil
	file_article_v1_article_proto_depIdxs = nil
}
