// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kratos-demo/internal/data/ent/article"
	"kratos-demo/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescCreatedAt is the schema descriptor for created_at field.
	articleDescCreatedAt := articleFields[3].Descriptor()
	// article.DefaultCreatedAt holds the default value on creation for the created_at field.
	article.DefaultCreatedAt = articleDescCreatedAt.Default.(func() time.Time)
	// articleDescUpdateAt is the schema descriptor for update_at field.
	articleDescUpdateAt := articleFields[4].Descriptor()
	// article.DefaultUpdateAt holds the default value on creation for the update_at field.
	article.DefaultUpdateAt = articleDescUpdateAt.Default.(func() time.Time)
}
